export type OwnerData = {
  _id?: string;
  createdById: string;
  name: string;
  active?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
  appointmentsTotal: number;
  ratingsTotal: number;
  haveDelivery: number;
  typeTax: string;
  costByTimeDriving?: number;
  fidelityTaxPoints?: number;
  fixedTax?: number;
  minimumTimeForReschedule?: number;
  description?: string;
  days1?: unknown;
  days2?: unknown;
  days3?: unknown;
  days4?: unknown;
  hourStart1?: string;
  hourStart2?: string;
  hourStart3?: string;
  hourStart4?: string;
  hourEnd1?: string;
  hourEnd2?: string;
  hourEnd3?: string;
  hourEnd4?: string;
  hourLunchStart1?: string;
  hourLunchEnd1?: string;
  hourLunchStart2?: string;
  hourLunchEnd2?: string;
  hourLunchStart3?: string;
  hourLunchEnd3?: string;
  hourLunchStart4?: string;
  hourLunchEnd4?: string;
};

export type OwnerPaginated = {
  owner: OwnerData[];
  total: number;
};

export class OwnerEntity {
  createdById: string;
  name: string;
  active?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
  appointmentsTotal: number;
  ratingsTotal: number;
  haveDelivery: number;
  typeTax: string;
  costByTimeDriving?: number;
  fidelityTaxPoints?: number;
  fixedTax?: number;
  minimumTimeForReschedule?: number;
  description?: string;
  days1?: unknown;
  days2?: unknown;
  days3?: unknown;
  days4?: unknown;
  hourStart1?: string;
  hourStart2?: string;
  hourStart3?: string;
  hourStart4?: string;
  hourEnd1?: string;
  hourEnd2?: string;
  hourEnd3?: string;
  hourEnd4?: string;
  hourLunchStart1?: string;
  hourLunchEnd1?: string;
  hourLunchStart2?: string;
  hourLunchEnd2?: string;
  hourLunchStart3?: string;
  hourLunchEnd3?: string;
  hourLunchStart4?: string;
  hourLunchEnd4?: string;

  constructor(data: OwnerData) {
    this.createdById = data.createdById;
    this.name = data.name;
    this.active = false;
    this.createdAt = new Date();
    this.updatedAt = new Date();
    this.appointmentsTotal = data.appointmentsTotal;
    this.ratingsTotal = data.ratingsTotal;
    this.haveDelivery = data.haveDelivery;
    this.typeTax = data.typeTax;
    this.costByTimeDriving = data.costByTimeDriving;
    this.fidelityTaxPoints = data.fidelityTaxPoints;
    this.fixedTax = data.fixedTax;
    this.minimumTimeForReschedule = data.minimumTimeForReschedule;
    this.description = data.description;
    this.days1 = data.days1;
    this.days2 = data.days2;
    this.days3 = data.days3;
    this.days4 = data.days4;
    this.hourStart1 = data.hourStart1;
    this.hourStart2 = data.hourStart2;
    this.hourStart3 = data.hourStart3;
    this.hourStart4 = data.hourStart4;
    this.hourEnd1 = data.hourEnd1;
    this.hourEnd2 = data.hourEnd2;
    this.hourEnd3 = data.hourEnd3;
    this.hourEnd4 = data.hourEnd4;
    this.hourLunchStart1 = data.hourLunchStart1;
    this.hourLunchEnd1 = data.hourLunchEnd1;
    this.hourLunchStart2 = data.hourLunchStart2;
    this.hourLunchEnd2 = data.hourLunchEnd2;
    this.hourLunchStart3 = data.hourLunchStart3;
    this.hourLunchEnd3 = data.hourLunchEnd3;
    this.hourLunchStart4 = data.hourLunchStart4;
    this.hourLunchEnd4 = data.hourLunchEnd4;
  }
}
