export type UserData = {
  _id?: string;
  createdById: string;
  name: string;
  email: string;
  role: string;
  confirmedEmail: boolean;
  sendedEmail: boolean;
  password: string;
  carId?: string;
  ownerId?: string;
  myOwnerId?: string;
  payDay: string;
  photoUrl: string;
  cpf: string;
  phone: string;
  coord?: unknown;
  distance?: number;
  appointmentsTotal?: number;
  plan?: string;
  cnpj?: string;
  city?: string;
  uf?: string;
  address?: string;
  complement?: string;
  photoId: string;
  cash?: boolean;
  creditCard?: boolean;
  debitCard?: boolean;
  transferBank?: boolean;
  check?: boolean;
  pix?: boolean;
  nextPlan?: string;
  addresses?: unknown;
  clientId?: string;
  active?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
};

export type UserPaginated = {
  user: UserData[];
  total: number;
};

export class UserEntity {
  createdById: string;
  name: string;
  email: string;
  role: string;
  confirmedEmail: boolean;
  sendedEmail: boolean;
  password: string;
  carId?: string;
  ownerId?: string;
  myOwnerId?: string;
  payDay: string;
  photoUrl: string;
  cpf: string;
  phone: string;
  coord?: unknown;
  distance?: number;
  appointmentsTotal?: number;
  plan?: string;
  cnpj?: string;
  city?: string;
  uf?: string;
  address?: string;
  complement?: string;
  photoId: string;
  cash?: boolean;
  creditCard?: boolean;
  debitCard?: boolean;
  transferBank?: boolean;
  check?: boolean;
  pix?: boolean;
  nextPlan?: string;
  addresses?: unknown;
  clientId?: string;
  active?: boolean;
  createdAt?: Date;
  updatedAt?: Date;

  constructor(data: UserData) {
    this.createdById = data.createdById;
    this.name = data.name;
    this.email = data.email;
    this.role = data.role;
    this.confirmedEmail = data.confirmedEmail;
    this.sendedEmail = data.sendedEmail;
    this.password = data.password;
    this.carId = data.carId;
    this.ownerId = data.ownerId;
    this.myOwnerId = data.myOwnerId;
    this.payDay = data.payDay;
    this.photoUrl = data.photoUrl;
    this.cpf = data.cpf;
    this.phone = data.phone;
    this.coord = data.coord;
    this.distance = data.distance;
    this.appointmentsTotal = data.appointmentsTotal;
    this.plan = data.plan;
    this.cnpj = data.cnpj;
    this.city = data.city;
    this.uf = data.uf;
    this.address = data.address;
    this.complement = data.complement;
    this.photoId = data.photoId;
    this.cash = data.cash;
    this.creditCard = data.creditCard;
    this.debitCard = data.debitCard;
    this.transferBank = data.transferBank;
    this.check = data.check;
    this.pix = data.pix;
    this.nextPlan = data.nextPlan;
    this.addresses = data.addresses;
    this.clientId = data.clientId;
    this.active = data.active;
    this.active = false;
    this.createdAt = new Date();
    this.updatedAt = new Date();
  }
}
